sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: zhangzhch/zhangzhch.github.io
    fqdn: blog.fluobo.cn
    target_branch: master
    email: zhangzhch2013@foxmail.com
    name: zhangzhch
