dist: xenial
language: go
addons:
  snaps:
  - hugo
install
  - snap install hugo

script:
  - hugo server

deploy:
  provider: pages
  skip-cleanup: true
  github-token: abb3decb305c77c2c412cd942043f77e50154969  # Set in travis-ci.org dashboard, marked secure
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master  # branch contains blog content
  on:
    branch: master  # branch contains Hugo generator code