env:
  - HUGO_VERSION="0.41"

language: go

go:
  - master # This uses automatically the latest version of go

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - gem install html-proofer

script:
  - hugo # This commands builds your website on travis

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: zhangzhch/zhangzhch.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: abb3decb305c77c2c412cd942043f77e50154969 # This is the authentication which you will setup in the next step in travis-ci dashboard
  on:
    branch: master