sudo: false
language: go
git:
    depth: 1

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="source"
    - DEPLOY_BRANCH="master"

install:
    - go get github.com/spf13/hugo 


script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: abb3decb305c77c2c412cd942043f77e50154969
    on:
        branch: master
    local_dir: public
    repo: zhangzhch/zhangzhch.github.io
    fqdn: blog.fluobo.cn
    target_branch: master
    email: zhangzhch2013@foxmail.com
    name: zhangzhch

